---
title: 'Twenty-First Century Storms'
author: "Jim Callahan"
date: "September 21, 2015"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---
### Synopsis:
Twenty-first century storms; a summary of the death toll, injuries and property damage.

### Data Processing
Load the NOAA storm data file.
```{r}
filename <- "~/GitHub/RepData_PeerAssessment2/data/repdata%2Fdata%2FStormData.csv.bz2"
NOAA <- read.csv(filename, 
                 stringsAsFactors = FALSE )
str(NOAA)
```


```{r}
#### Select Columns of interest:
####        Primary key:    REFNUM
####        Date and Time:  BGN_DATE, BGN_TIME, 
####        Location:       STATE, COUNTY, COUNTY_END, LATITUDE, LONGITUDE,
####        Type of Storm:  EVTYPE,
####        Damage:         PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP,
####        Casualties:     FATALITIES, INJURIES

# storms <- subset(NOAA, select())
columnsubset <- c("REFNUM", "BGN_DATE", "BGN_TIME", "TIME_ZONE",
                  "STATE", "COUNTY", "COUNTY_END", "LATITUDE", "LONGITUDE", 
                  "EVTYPE", "PROPDMG", "PROPDMGEXP", "CROPDMG", "CROPDMGEXP", 
                  "FATALITIES", "INJURIES")

#### Select Rows of interest (exclude freakish events without impact):
#### Select only observations with at least one injury (or fatality) 
####         or non-zero property damage (or crop damage).
# rowsubset <- "NOAA$INJURIES > 0 || NOAA$FATALITIES > 0 || NOAA$PROPDMG > 0 || NOAA$CROPDMG > 0"


storms <- NOAA[, columnsubset]
str(storms)


#### Select years of interest (Since 2001 "21st Century Storms" or last 25 years)

#### Step 1: Create a year variable from date
# datetime = as.POSIXct(storms$BGN_DATE, "%m/%d/%Y %H:%M:%S", tz = storms$TIME_ZONE)
datetime = as.POSIXct(storms$BGN_DATE, "%m/%d/%Y %H:%M:%S", tz = "EST")
storms$year <- format(datetime, "%Y")

#### Step 2: Filter by year
storms <- storms[as.numeric(storms$year) >= 2001, ]

#### Remove the original NOAA database
rm(NOAA)

```

```{r}
#### Scale Property Damage and Crop Damage by thouands and millions
storms$PropertyDamage <- storms$PROPDMG
storms$CropDamage     <- storms$CROPDMG

with(storms, 
     {
         PropertyDamage <- ifelse(PROPDMGEXP == "K", PROPDMG * 1000, PROPDMG)
         PropertyDamage <- ifelse(PROPDMGEXP == "M", PROPDMG * 1000 * 1000, PROPDMG)
         
         CropDamage     <- ifelse(CROPDMGEXP == "K", CROPDMG * 1000, CROPDMG)
         CropDamage     <- ifelse(CROPDMGEXP == "M", CROPDMG * 1000 * 1000, CROPDMG)
     }
)

#### Rename and put variables in logical order.


```



### Results
#### Tabulate Fatalities and Damage by Storm Type

```{r}
# Tabulate Fatalities and Damage by Storm Type
# R commands include table(), xtabs() and ftable()  -- or "aggregate()"
#### Severe Storm Events -- type and frequency
#### Jared Lander's "R for Everyone" page 123
stormtab <- aggregate(cbind(FATALITIES, INJURIES, PropertyDamage, CropDamage) 
                      ~ EVTYPE + year, storms, sum)
stormtab

```

#### Health Impact

#### Economic Impact



# END

